### ISSUE TITLE
Amount of Lines for lambda_handler()

### ISSUE THREAD

**Issue by jszeto9190** [ryan-spencer1220/restaurant-information-microservice#1]
It would be beneficial to the code if lambda_handler() of lambda_function.py was broken down in to multiple functions of 10 lines or fewer.

**Comment by ryan-spencer1220** [comment]
Are you having issues with performance? Or is that just a 'best practice' suggestion?

**Comment by jszeto9190** [comment]
No performance issues! It's just a best practice suggestion per the discussion assignment's instructions to make code less "smelly".

**Comment by ryan-spencer1220** [comment]
Cool! I can work on refactoring tonight.

**Comment by ryan-spencer1220** [comment]
lambda_handler was broken into three functions to reduce number of jobs handled by one function and reduce overall lines of code per function.
